# Generated by Django 3.0 on 2019-12-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
