# Generated by Django 3.0 on 2019-12-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191215_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='django'),
            preserve_default=False,
        ),
    ]
