# Generated by Django 3.0 on 2019-12-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
    ]
